# steps:
# - name: gcr.io/ludosample-d66f6/firebase
#   args: ['deploy', '--project=ludosample-d66f6', '--only=hosting']
#   # args: ['deploy', '--project=ludosample-d66f6', '--only', 'functions']
# options:
#   defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
    # - name: 'gcr.io/cloud-builders/gcloud'
     - name: 'gcr.io/terraformer-376507/firebase'
       entrypoint: 'bash'
       args:
         - '-c'
         - |
           if [[ "$_COMMIT_MESSAGE" == *"updated"* ]]; then
             echo "Deploying Firebase Function"
             firebase use --add --token $_FIREBASE_TOKEN --project terraformer-376507
             firebase deploy --only hosting
           else
             echo "Firebase deployment needed for the latestcommit."
           fi
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
   
